"""deleted _ from Runningstats model

Revision ID: 65a476d458fb
Revises: ba2601eaabb5
Create Date: 2020-12-18 10:38:44.571712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a476d458fb'
down_revision = 'ba2601eaabb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('running_stats', sa.Column('fiftyk_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('fiftym_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('fivek_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('half_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('hundredm_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('hundrek_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('marathon_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('mile_pr', sa.String(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('tenk_pr', sa.String(length=10), nullable=True))
    op.drop_column('running_stats', '_10k_pr')
    op.drop_column('running_stats', '_100m_pr')
    op.drop_column('running_stats', '_50k_pr')
    op.drop_column('running_stats', '_half_pr')
    op.drop_column('running_stats', '_50m_pr')
    op.drop_column('running_stats', '_5k_pr')
    op.drop_column('running_stats', '_100k_pr')
    op.drop_column('running_stats', '_mile_pr')
    op.drop_column('running_stats', '_marathon_pr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('running_stats', sa.Column('_marathon_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_mile_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_100k_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_5k_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_50m_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_half_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_50k_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_100m_pr', sa.VARCHAR(length=10), nullable=True))
    op.add_column('running_stats', sa.Column('_10k_pr', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('running_stats', 'tenk_pr')
    op.drop_column('running_stats', 'mile_pr')
    op.drop_column('running_stats', 'marathon_pr')
    op.drop_column('running_stats', 'hundrek_pr')
    op.drop_column('running_stats', 'hundredm_pr')
    op.drop_column('running_stats', 'half_pr')
    op.drop_column('running_stats', 'fivek_pr')
    op.drop_column('running_stats', 'fiftym_pr')
    op.drop_column('running_stats', 'fiftyk_pr')
    # ### end Alembic commands ###
