"""renamed hundredk

Revision ID: 77c3cc75ef31
Revises: dcdd023f5539
Create Date: 2020-12-21 10:25:57.655279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c3cc75ef31'
down_revision = 'dcdd023f5539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runningstatistics', sa.Column('hundredk_pr', sa.String(length=10), nullable=True))
    op.drop_column('runningstatistics', 'hundrek_pr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runningstatistics', sa.Column('hundrek_pr', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('runningstatistics', 'hundredk_pr')
    # ### end Alembic commands ###
