"""empty message

Revision ID: 83fff426ff3b
Revises: 77c3cc75ef31
Create Date: 2020-12-21 11:04:11.781593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fff426ff3b'
down_revision = '77c3cc75ef31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'runningstatistics', ['user_id'])
    op.drop_column('runningstatistics', 'hundrek_pr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runningstatistics', sa.Column('hundrek_pr', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'runningstatistics', type_='unique')
    # ### end Alembic commands ###
