"""add runnin_stats to User model

Revision ID: ba2601eaabb5
Revises: f3da830878fc
Create Date: 2020-12-18 09:28:19.491134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2601eaabb5'
down_revision = 'f3da830878fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('running_stats', sa.Column('most_races_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_stats', 'most_races_year')
    # ### end Alembic commands ###
