"""renamed running stats form

Revision ID: e52eca539eae
Revises: 65a476d458fb
Create Date: 2020-12-18 10:50:21.809010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52eca539eae'
down_revision = '65a476d458fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('running_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mile_pr', sa.String(length=10), nullable=True),
    sa.Column('fivek_pr', sa.String(length=10), nullable=True),
    sa.Column('tenk_pr', sa.String(length=10), nullable=True),
    sa.Column('half_pr', sa.String(length=10), nullable=True),
    sa.Column('marathon_pr', sa.String(length=10), nullable=True),
    sa.Column('fiftyk_pr', sa.String(length=10), nullable=True),
    sa.Column('hundrek_pr', sa.String(length=10), nullable=True),
    sa.Column('fiftym_pr', sa.String(length=10), nullable=True),
    sa.Column('hundredm_pr', sa.String(length=10), nullable=True),
    sa.Column('running_streak_pr', sa.Integer(), nullable=True),
    sa.Column('annual_miles_pr', sa.Integer(), nullable=True),
    sa.Column('most_races_year', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('running_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('running_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('_mile_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_5k_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_10k_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_half_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_marathon_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_50k_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_100k_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_50m_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('_100m_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('running_streak_pr', sa.INTEGER(), nullable=True),
    sa.Column('annual_miles_pr', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('most_races_year', sa.INTEGER(), nullable=True),
    sa.Column('fiftyk_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('fiftym_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('fivek_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('half_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('hundredm_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('hundrek_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('marathon_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('mile_pr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tenk_pr', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('running_statistics')
    # ### end Alembic commands ###
