"""added runningstats model

Revision ID: f3da830878fc
Revises: 757b49078248
Create Date: 2020-12-17 21:59:48.900263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3da830878fc'
down_revision = '757b49078248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('running_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_mile_pr', sa.String(length=10), nullable=True),
    sa.Column('_5k_pr', sa.String(length=10), nullable=True),
    sa.Column('_10k_pr', sa.String(length=10), nullable=True),
    sa.Column('_half_pr', sa.String(length=10), nullable=True),
    sa.Column('_marathon_pr', sa.String(length=10), nullable=True),
    sa.Column('_50k_pr', sa.String(length=10), nullable=True),
    sa.Column('_100k_pr', sa.String(length=10), nullable=True),
    sa.Column('_50m_pr', sa.String(length=10), nullable=True),
    sa.Column('_100m_pr', sa.String(length=10), nullable=True),
    sa.Column('running_streak_pr', sa.Integer(), nullable=True),
    sa.Column('annual_miles_pr', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('running_stats')
    # ### end Alembic commands ###
